### ISSUE TITLE
Resizable popup is  jumping when I'm trying to resize if used in combination with bootstrap modal popup and angular2-draggable

### ISSUE THREAD

**Issue by SivaPrakashK90** [mattlewis92/angular-resizable-element#77] opened 2017-11-20 11:34 UTC
I'm using angular-resizable-element to resize the modal popup in the combination of angular2-draggable but when I'm trying to hold the popup to resize it. it is jumping to somewhere on the screen.
 here is my sample code.

<button class="btn btn-lg btn-outline-primary" (click)="openSample(modalPopup)">Launch demo modal</button>

<ng-template #modalPopup let-c="close" let-d="dismiss">
  <div ngDraggable [handle]="divDraggable" class="card" [ngStyle]="style" mwlResizable [validateResize]="validate" [resizeEdges]="{bottom: true, right: true, top: true, left: true}"
    [enableGhostResize]="true" [resizeSnapGrid]="{left: 50, right: 50}" (resizeEnd)="onResizeEnd($event)" style="min-width:650px; min-height:650px">
    <div #divDraggable class="modal-header card-header">
      <h4 class="modal-title">Sample Popup</h4>
      <button type="button" class="close" aria-label="Close" (click)="d('Cross click')">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum quibusdam architecto voluptas reprehenderit voluptate hic aperiam
      ratione nesciunt, delectus dolorem quod, quidem error. Autem tenetur, quod illum ullam provident totam.
    </div>
  </div>
</ng-template>

component.
`import { Component, OnInit, AfterViewInit } from '@angular/core';
import { NgbModal, NgbModalOptions } from "@ng-bootstrap/ng-bootstrap";
import { AngularDraggableModule } from 'angular2-draggable';
import { ResizeEvent } from 'angular-resizable-element';
declare var jquery: any;
declare var $: any;
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements AfterViewInit {
  title = 'Angular';
 ngAfterViewInit() {
}

  openSample(content) {
    debugger;
    let options: NgbModalOptions = {
      size: "lg"
      , backdrop: 'static'
    };
    this.modalService.open(content, options).result.then((result) => {
      this.closeResult = `Closed with: ${result}`;
    }, (reason) => {
      this.closeResult = `Dismissed ${this.getDismissReason(reason)}`;
    });
    $(".modal-content").css("visibility", "hidden");
    $(".modal-content").children().css("visibility", "visible");
  }
 onResizeEnd(event: ResizeEvent): void {
      debugger;
      this.style = {
          position: 'fixed',
          left: `${event.rectangle.left}px`,
          top: `${event.rectangle.top}px`,
          width: `${event.rectangle.width}px`,
          height: `${event.rectangle.height}px`
      };
      $(".modal-content").css("visibility", "visible");
      $(".modal-content").children().css("visibility", "visible");
  }
  }
  `
help me how to resolve this issue ?

**Comment by mattlewis92** [comment] 2017-12-26 17:25
Closing as a duplicate of https://github.com/mattlewis92/angular-resizable-element/issues/77

**Closed by mattlewis92** 2017-12-26 17:25 UTC
